CLIP_EPSILON: 0.2
CRITIC_LOSS_COEF: 1.0
DATA_FILE: ./sensor_data/spire_5_[44.4901162203284, 11.3398356513878].csv
DATA_FOLDER: ./generated_data/20250417_130123
ENTROPY_COEF: 0.0
EPOCHS: 100
GAMMA: 1.0
LAMBDA_GAE: 1.0
LEARNING_RATE_ACTOR: 0.0001
LEARNING_RATE_CRITIC: 0.001
LSTM_UNITS: 32
MODEL_PATH: best_model.keras
NUM_STEPS_TO_GENERATE: 24
N_FEATURES: 1
N_STEPS_IN: 24
PPO_MINIBATCH_SIZE: 64
PPO_UPDATE_EPOCHS: 4
REGULARIZATION_COEF: 1
SAMPLING_SIGMA: 0.01
SEED: 42
TRAJECTORY_BATCH_SIZE: 16
