apiVersion: batch/v1
kind: Job
metadata:
  name: converting-job
  labels:
    app: converting-lite
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: converting-lite
          image: lucaserf/converting-lite:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /var/data/
          env:
            - name: FOLDER_PATH
              value: "/var/data/"
            - name: MODEL_PATH
              value: "regression_model_tf_prova.keras"
            - name: OUTPUT_PATH
              value: "regression_model_lite"
      restartPolicy: Never
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
