apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-deploy
  labels:
    app: drift-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drift-detection
  template:
    metadata:
      name: drift-detection
      labels:
        app: drift-detection
    spec:
      containers:
        - name: drift-detection
          image: lucaserf/drift_detection:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /var/data/
          env:
            - name: FOLDER_PATH
              value: /var/data/
            - name: BROKER_ADDRESS
              value: "as-sensiblecity1.cloudmmwunibo.it"
            - name: "TOPIC_NAME"
              value: "drift-detection"
            - name: "BATCH_SIZE"
              value: "100"
            - name: "ALPHA_P_VALUE"
              value: "0.001"
            - name: "OUTPUT_NAME"
              value: "drift_data.csv"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
