[package]
name = "synthetic-data-regressor"
version = "0.1.0"
authors = ["lucaserf"]
readme = "README.md"
edition = "2021"
publish = false

[dependencies]
wasi-nn = "0.4.0"
csv = "1.1.6"

[workspace]
