apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
  labels:
    app: training-regression
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: training-regression
          image: lucaserf/training-regression:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /var/data/
      restartPolicy: Never
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
