apiVersion: batch/v1
kind: Job
metadata:
  name: training-job-test
  labels:
    app: training-regression
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: training-regression
          image: lucaserf/training-regression:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /var/data/
          env:
            - name: FOLDER_PATH
              value: "/var/data/"
            - name: OUTPUT_PATH
              value: "regression_model_tf_prova"
            - name: DATA_PATH
              value: "data.csv"
            - name: LOGGING_LEVEL
              value: "INFO"
      restartPolicy: Never
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
