apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-tflite-deploy
  labels:
    app: python-tflite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-tflite
  template:
    metadata:
      name: python-tflite
      labels:
        app: python-tflite
    spec:
      containers:
        - image: lucaserf/python_tflite:latest
          imagePullPolicy: Always
          name: python-tflite
          volumeMounts:
            - name: data-volume
              mountPath: /var/data/
          env:
            - name: MODEL_NAME
              value: model_regression.tflite
            - name: MODEL_PATH
              value: /var/data/
            - name: BATCH_SIZE
              value: "10"
            - name: TOPIC_NAME
              value: "drift-detection"
            - name: BROKER_ADDRESS
              value: "broker.hivemq.com"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
